### ISSUE TITLE
日记 闪退

### ISSUE THREAD

**Issue by bczhc** [bczhc/some-tools#175]

**Comment by bczhc** [comment]
长文本保存和频繁切入切出会出现闪退

**Comment by bczhc** [comment]
Java层
莫名其妙返回闪退

java.lang.RuntimeException: Unable to destroy activity {pers.zhc.tools/pers.zhc.tools.diary.DiaryTakingActivity}: java.lang.Exception: database is locked
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5155)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5174)
	at android.app.ActivityThread.-wrap6(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2058)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.Exception: database is locked
	at pers.zhc.tools.jni.JNI$Sqlite3.exec(Native Method)
	at pers.zhc.tools.utils.sqlite.MySQLite3.exec(MySQLite3.java:29)
	at pers.zhc.tools.utils.sqlite.MySQLite3.exec(MySQLite3.java:33)
	at pers.zhc.tools.diary.DiaryTakingActivity.save(DiaryTakingActivity.java:152)
	at pers.zhc.tools.diary.DiaryTakingActivity.onDestroy(DiaryTakingActivity.java:135)
	at android.app.Activity.performDestroy(Activity.java:7615)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1253)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5142)
	... 9 more
java.lang.Exception: database is locked
	at pers.zhc.tools.jni.JNI$Sqlite3.exec(Native Method)
	at pers.zhc.tools.utils.sqlite.MySQLite3.exec(MySQLite3.java:29)
	at pers.zhc.tools.utils.sqlite.MySQLite3.exec(MySQLite3.java:33)
	at pers.zhc.tools.diary.DiaryTakingActivity.save(DiaryTakingActivity.java:152)
	at pers.zhc.tools.diary.DiaryTakingActivity.onDestroy(DiaryTakingActivity.java:135)
	at android.app.Activity.performDestroy(Activity.java:7615)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1253)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5142)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5174)
	at android.app.ActivityThread.-wrap6(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2058)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by bczhc** [comment]
> Java层
> 莫名其妙返回闪退
> 
> > java.lang.RuntimeException: Unable to destroy activity {pers.zhc.tools/pers.zhc.tools.diary.DiaryTakingActivity}: java.lang.Exception: database is locked
> > at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5155)
> > at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5174)
> > at android.app.ActivityThread.-wrap6(Unknown Source:0)
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2058)
> > at android.os.Handler.dispatchMessage(Handler.java:108)
> > at android.os.Looper.loop(Looper.java:166)
> > at android.app.ActivityThread.main(ActivityThread.java:7529)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
> > Caused by: java.lang.Exception: database is locked
> > at pers.zhc.tools.jni.JNI$Sqlite3.exec(Native Method)
> > at pers.zhc.tools.utils.sqlite.MySQLite3.exec(MySQLite3.java:29)
> > at pers.zhc.tools.utils.sqlite.MySQLite3.exec(MySQLite3.java:33)
> > at pers.zhc.tools.diary.DiaryTakingActivity.save(DiaryTakingActivity.java:152)
> > at pers.zhc.tools.diary.DiaryTakingActivity.onDestroy(DiaryTakingActivity.java:135)
> > at android.app.Activity.performDestroy(Activity.java:7615)
> > at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1253)
> > at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5142)
> > ... 9 more
> > java.lang.Exception: database is locked
> > at pers.zhc.tools.jni.JNI$Sqlite3.exec(Native Method)
> > at pers.zhc.tools.utils.sqlite.MySQLite3.exec(MySQLite3.java:29)
> > at pers.zhc.tools.utils.sqlite.MySQLite3.exec(MySQLite3.java:33)
> > at pers.zhc.tools.diary.DiaryTakingActivity.save(DiaryTakingActivity.java:152)
> > at pers.zhc.tools.diary.DiaryTakingActivity.onDestroy(DiaryTakingActivity.java:135)
> > at android.app.Activity.performDestroy(Activity.java:7615)
> > at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1253)
> > at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5142)
> > at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5174)
> > at android.app.ActivityThread.-wrap6(Unknown Source:0)
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2058)
> > at android.os.Handler.dispatchMessage(Handler.java:108)
> > at android.os.Looper.loop(Looper.java:166)
> > at android.app.ActivityThread.main(ActivityThread.java:7529)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

可能还是连接键盘页面重新调用onCreate方法的原因，数据库没有关闭。

**Comment by bczhc** [comment]
> 过长文本保存和频繁切入切出会出现闪退 jni层的

长文本那个是单引号问题，内容中包含单引号就会闪退。

**Comment by bczhc** [comment]
还有单引号问题，内容中包含单引号就会闪退。

**Comment by bczhc** [comment]
还要时时保存，写的时候就要保存，以防万一，否则万一写的时候崩溃了，内容就会丢失。
