### ISSUE TITLE
输入法闪退 未知触发

### ISSUE THREAD

**Issue by bczhc** [bczhc/some-tools#187]
MEIZU_FINGERPRINT: 7.0-1575051377_stable
SUPPORTED_64_BIT_ABIS: [Ljava.lang.String;@1f061fa
BOARD: M1E
BOOTLOADER: unknown
TYPE: user
ID: NRD90M
TIME: 1575053214000
BRAND: Meizu
TAG: Build
HARDWARE: mt6755
SERIAL: A02AECP82AWGY
SUPPORTED_ABIS: [Ljava.lang.String;@29013ab
CPU_ABI: arm64-v8a
IS_DEBUGGABLE: false
RADIO: unknown
MANUFACTURER: Meizu
IS_EMULATOR: false
SUPPORTED_32_BIT_ABIS: [Ljava.lang.String;@3e8cc25
TAGS: release-keys
CPU_ABI2: 
UNKNOWN: unknown
PERMISSIONS_REVIEW_REQUIRED: false
USER: flyme
DEBUG: true
FINGERPRINT: Meizu/meizu_M1E/M1E:7.0/NRD90M/1575052815:user/release-keys
HOST: Mz-Builder-l3
PRODUCT: meizu_M1E
DISPLAY: Flyme 8.0.0.0A
MODEL: M1 E
DEVICE: M1E
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.deleteCharAt(AbstractStringBuilder.java:792)
	at java.lang.StringBuilder.deleteCharAt(StringBuilder.java:259)
	at pers.zhc.tools.inputmethod.WubiIME$1.onKeyDown(WubiIME.java:141)
	at pers.zhc.tools.inputmethod.KeyEventResolver.onKeyDown(KeyEventResolver.java:23)
	at pers.zhc.tools.inputmethod.WubiIME.onKeyDown(WubiIME.java:337)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2749)
	at android.inputmethodservice.AbstractInputMethodService$AbstractInputMethodSessionImpl.dispatchKeyEvent(AbstractInputMethodService.java:136)
	at android.inputmethodservice.IInputMethodSessionWrapper$ImeInputEventReceiver.onInputEvent(IInputMethodSessionWrapper.java:232)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:191)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:328)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:6560)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)

**Comment by bczhc** [comment]
好久没有出现过这个bug了，我也定位不到了，也不知道是什么时候的bug了……那就不管了吧。
