### ISSUE TITLE
笔记全选删除会闪退

### ISSUE THREAD

**Issue by bczhc** [bczhc/some-tools#193]
未知触发

删除倒是成功的

Crash:
>$jacocoData: [Z@480d536
SUPPORTED_64_BIT_ABIS: [Ljava.lang.String;@52205a4
BOARD: QC_Reference_Phone
BOOTLOADER: unknown
TYPE: user
BUILD_TYPE: debug
ID: NMF26F
TIME: 1587958031000
BRAND: vivo
TAG: Build
SERIAL: b46e5554
HARDWARE: qcom
SUPPORTED_ABIS: [Ljava.lang.String;@e0c8f0d
CPU_ABI: arm64-v8a
VERSION_NAME: 1.0.0-20210217161004-馃Н馃馃拋
IS_DEBUGGABLE: false
RADIO: unknown
VERSION_CODE: 202102170
MANUFACTURER: vivo
IS_EMULATOR: false
SUPPORTED_32_BIT_ABIS: [Ljava.lang.String;@9956c37
TAGS: release-keys
CPU_ABI2: 
UNKNOWN: unknown
PERMISSIONS_REVIEW_REQUIRED: false
USER: compiler
DEBUG: true
FINGERPRINT: vivo/PD1610/PD1610:7.1.1/NMF26F/compil04271127:user/release-keys
HOST: compiler01104
PRODUCT: PD1610
DISPLAY: NMF26F release-keys
MODEL: vivo Xplay6
DEVICE: PD1610
APPLICATION_ID: pers.zhc.tools
Exception in thread "main" android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@bba8d6f is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
	at android.widget.Toast$TN.handleShow(Toast.java:506)
	at android.widget.Toast$TN$2.handleMessage(Toast.java:389)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)

**Comment by bczhc** [comment]
而且删除要很久，很卡。猜测是不是每删除一条就又刷新了view。。

**Comment by bczhc** [comment]
![Uploading 截屏_20210314_091952.jpg…]()

**Comment by bczhc** [comment]
![截屏_20210314_091952](https://user-images.githubusercontent.com/49330580/111054318-968a0f80-84a6-11eb-9b78-ed5702798a36.jpg)
