### ISSUE TITLE
日记 附件 代办bugs

### ISSUE THREAD

**Issue by bczhc** [bczhc/some-tools#197]

**Comment by bczhc** [comment]
有时，可能是在导入合法数据库之后，再导入非数据库文件，又异常：
> BOARD: LND-AL30
APPLICATION_ID: pers.zhc.tools
CPU_ABI2: 
HOST: cn-central-1b-da10f2c581594319627369-772111192-ff7kz
IS_TREBLE_ENABLED: true
SUPPORTED_64_BIT_ABIS: [Ljava.lang.String;@7c426d0
CPU_ABI: arm64-v8a
PERMISSIONS_REVIEW_REQUIRED: false
IS_USERDEBUG: false
DISPLAY: LND-AL30 8.0.0.235(C00)
SUPPORTED_ABIS: [Ljava.lang.String;@73816c9
FINGERPRINTEX: HONOR/LND-AL30/HWLND-Q:8.0.0/HONORLND-AL30/238(C00):user/release-keys
FINGERPRINT: HONOR/LND-AL30/HWLND-Q:8.0.0/HONORLND-AL30/235(C00):user/release-keys
PRODUCT: LND-AL30
HIDE_PRODUCT_INFO: false
ID: HONORLND-AL30
replacements: [Ljava.lang.String;@4c458ef
HWFINGERPRINT: //
TYPE: user
SERIAL: 73EBB18621217594
NO_HOTA: false
IS_CONTAINER: false
IS_ENG: false
BUILD_TYPE: debug
DEVICE: HWLND-Q
$jacocoData: [Z@83f9acd
VERSION_CODE: 202104080
TIME: 1594318977000
IS_USER: true
MODEL: LND-AL30
MANUFACTURER: HUAWEI
USER: test
DEBUG: true
BRAND: HONOR
VERSION_NAME: 1.0.0-20210408231436-🛯🤹😊
SUPPORTED_32_BIT_ABIS: [Ljava.lang.String;@8cbe693
matchers: [Ljava.lang.String;@24921ce
HARDWARE: qcom
IS_DEBUGGABLE: false
BOOTLOADER: unknown
RADIO: unknown
TAG: Build
UNKNOWN: unknown
IS_EMULATOR: false
TAGS: release-keys
Exception in thread "Thread-24" java.lang.RuntimeException: execution failed, error code: 26, msg: file is not a database
	at pers.zhc.tools.jni.JNI$Sqlite3.exec(Native Method)
	at pers.zhc.tools.utils.sqlite.SQLite3.exec(SQLite3.java:44)
	at pers.zhc.tools.diary.DiaryMainActivity.lambda$loadListViews$9$DiaryMainActivity(DiaryMainActivity.java:500)
	at pers.zhc.tools.diary.-$$Lambda$DiaryMainActivity$6Ma_m8MXJX0VRYK0NDYJpJAc1Xs.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:784)
