### ISSUE TITLE
Magic滑动的时候返回崩溃

### ISSUE THREAD

**Issue by bczhc** [bczhc/some-tools#200]
```
BOARD: LND-AL30
APPLICATION_ID: pers.zhc.tools
CPU_ABI2: 
HOST: cn-central-1b-da10f2c581594319627369-772111192-ff7kz
IS_TREBLE_ENABLED: true
SUPPORTED_64_BIT_ABIS: [Ljava.lang.String;@fe5f6d8
CPU_ABI: arm64-v8a
PERMISSIONS_REVIEW_REQUIRED: false
IS_USERDEBUG: false
DISPLAY: LND-AL30 8.0.0.235(C00)
SUPPORTED_ABIS: [Ljava.lang.String;@9301a31
FINGERPRINTEX: HONOR/LND-AL30/HWLND-Q:8.0.0/HONORLND-AL30/251(C00):user/release-keys
FINGERPRINT: HONOR/LND-AL30/HWLND-Q:8.0.0/HONORLND-AL30/235(C00):user/release-keys
PRODUCT: LND-AL30
HIDE_PRODUCT_INFO: false
ID: HONORLND-AL30
replacements: [Ljava.lang.String;@d5a4e97
HWFINGERPRINT: //
TYPE: user
SERIAL: 73EBB18621217594
NO_HOTA: false
IS_CONTAINER: false
IS_ENG: false
BUILD_TYPE: debug
DEVICE: HWLND-Q
VERSION_CODE: 202107100
TIME: 1594318977000
IS_USER: true
MODEL: LND-AL30
MANUFACTURER: HUAWEI
USER: test
DEBUG: true
BRAND: HONOR
VERSION_NAME: 1.0.0-20210710154938-🚞😁🚒
SUPPORTED_32_BIT_ABIS: [Ljava.lang.String;@de251bb
matchers: [Ljava.lang.String;@45c4516
HARDWARE: qcom
IS_DEBUGGABLE: false
BOOTLOADER: unknown
RADIO: unknown
TAG: Build
UNKNOWN: unknown
IS_EMULATOR: false
TAGS: release-keys
Exception in thread "main" java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 44(offset:44).state:82 androidx.recyclerview.widget.RecyclerView{59ed13b VFED..... .......D 10,48-710,1190 #7f0900c0 app:id/file_list_rv}, adapter:pers.zhc.tools.magic.FileListActivity$MyAdapter@535fd2b, layout:androidx.recyclerview.widget.LinearLayoutManager@5621588, context:pers.zhc.tools.magic.FileListActivity@807f07a
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6364)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

```

**Comment by bczhc** [comment]
崩溃崩溃崩溃
