### ISSUE TITLE
悬浮画板：拼手速产生的弹窗错乱导致的顺序错乱导致闪退 

### ISSUE THREAD

**Issue by bczhc** [bczhc/some-tools#32]
重现：按隐藏时拼手速按关闭悬浮窗，先关闭，然后底下的那个弹窗再点击隐藏按钮。

> BOARD=LLD-AL10
CPU_ABI2=
HOST=wh22cb47ad901557827632507-348413158-337lw
versionName=4.6.1.1_20200110
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@abbaf25
CPU_ABI=arm64-v8a
PERMISSIONS_REVIEW_REQUIRED=false
DISPLAY=LLD-AL10 9.1.0.113(C00E111R1P10)
SUPPORTED_ABIS=[Ljava.lang.String;@ce508fa
FINGERPRINT=HONOR/LLD-AL10/HWLLD-H:9/HONORLLD-AL10/113C00:user/release-keys
PRODUCT=LLD-AL10
HIDE_PRODUCT_INFO=false
ID=HONORLLD-AL10
replacements=[Ljava.lang.String;@7672908
HWFINGERPRINT=///LLD-LGRP1-CHN 9.1.0.113/LLD-AL10-CUST 9.1.0.111(C00)/LLD-AL10-PRELOAD 9.1.0.10(C00R1)//
TYPE=user
SERIAL=unknown
NO_HOTA=false
DEVICE=HWLLD-H
TIME=1557833742000
MODEL=LLD-AL10
MANUFACTURER=HUAWEI
USER=test
versionCode=20200110
BRAND=HONOR
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@a07b71c
matchers=[Ljava.lang.String;@19d2eab
HARDWARE=hi6250
IS_DEBUGGABLE=false
BOOTLOADER=unknown
RADIO=unknown
UNKNOWN=unknown
IS_EMULATOR=false
TAGS=release-keys
java.lang.IllegalArgumentException: View=android.widget.LinearLayout{ed99d8 V.E...... ......ID 0,0-84,1476} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:547)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:439)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:210)
	at pers.zhc.tools.floatingboard.FloatingBoardMainActivity.hide(FloatingBoardMainActivity.java:570)
	at pers.zhc.tools.floatingboard.FloatingBoardMainActivity.lambda$null$9$FloatingBoardMainActivity(FloatingBoardMainActivity.java:461)
	at pers.zhc.tools.floatingboard.-$$Lambda$FloatingBoardMainActivity$T_G-J48Tl_iRenw66eM6YCBbyF0.onClick(Unknown Source:2)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:174)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7593)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by bczhc** [comment]
使用try...catch解决。。
